Update requirements.txt
Fix another dependency error

pip install -r requirements.txt
Requirement already satisfied: certifi==2021.10.8 in c:\python311\lib\site-packages (from -r requirements.txt (line 1)) (2021.10.8)
Requirement already satisfied: charset-normalizer==2.0.7 in c:\python311\lib\site-packages (from -r requirements.txt (line 2)) (2.0.7)
Requirement already satisfied: idna==3.3 in c:\python311\lib\site-packages (from -r requirements.txt (line 3)) (3.3)
Requirement already satisfied: python-sonarqube-api==1.2.4.post0 in c:\python311\lib\site-packages (from -r requirements.txt (line 4)) (1.2.4.post0)
Collecting requests==2.26.0 (from -r requirements.txt (line 5))
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Requirement already satisfied: urllib3==1.26.7 in c:\python311\lib\site-packages (from -r requirements.txt (line 6)) (1.26.7)
Installing collected packages: requests
  Attempting uninstall: requests
    Found existing installation: requests 2.28.2
    Uninstalling requests-2.28.2:
      Successfully uninstalled requests-2.28.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
duckduckgo-search 2.8.5 requires requests>=2.28.2, but you have requests 2.26.0 which is incompatible.
gtts 2.3.1 requires requests<3,>=2.27, but you have requests 2.26.0 which is incompatible.